# Generated by Django 4.2.3 on 2024-05-21 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicalsApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicaldata',
            name='componentName',
            field=models.CharField(choices=[('hw', 'Height / Weight'), ('bp', 'Blood Pressure'), ('heartrate', 'Heart Rate')], max_length=20),
        ),
    ]
