# Generated by Django 5.0.6 on 2024-05-22 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicalsApp', '0003_mymodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='date',
            field=models.CharField(max_length=30),
        ),
    ]
