# Generated by Django 5.0.6 on 2024-05-23 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicalsApp', '0005_mymodel_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='date',
            field=models.DateField(max_length=30),
        ),
    ]
